name: CI

on:
  push:
    branches: [ main, develop, 'release/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        
    - name: Build and verify both JUnit 4 JS tests and JUnit 5 Java tests are running
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Running mvn verify and checking both JUnit 4 JavaScript and JUnit 5 Java test execution..."
        
        # Run mvn verify and capture output (allow test failures for demo purposes)
        mvn verify 2>&1 | tee build.log || true
        
        # Verify JUnit 4 JavaScript tests are running
        echo "Checking JUnit 4 JavaScript tests..."
        if ! grep -q "One == One" build.log; then
          echo "ERROR: JavaScript test 'One == One' output not found - JS tests may not be running!"
          exit 1
        fi
        
        if ! grep -q "Hello World" build.log; then
          echo "ERROR: JavaScript test 'Hello World' output not found - JS tests may not be running!"
          exit 1
        fi
        
        # Check that we ran the expected number of JavaScript tests (5)
        if ! grep -q "Tests run: 5.*ExampleTestSuite" build.log; then
          echo "ERROR: Expected 'Tests run: 5' for ExampleTestSuite not found - wrong number of JavaScript tests executed!"
          grep "Tests run:" build.log || echo "No 'Tests run:' found at all"
          exit 1
        fi
        
        # Check total test count (31 total: 5 JS + 6 JUnit 5 + 4 GraalVM debug + 16 GraalVM crypto)
        if ! grep -q "Tests run: 31, Failures: 0, Errors: 0, Skipped: 0" build.log; then
          echo "ERROR: Expected total 'Tests run: 31' not found - wrong total test count!"
          grep "Tests run:" build.log || echo "No 'Tests run:' found at all"
          exit 1
        fi
        
        # Verify JUnit 5 Java tests are running
        echo "Checking JUnit 5 Java tests..."
        if ! grep -q "Running JUnit 5" build.log; then
          echo "ERROR: JUnit 5 test output not found - JUnit 5 tests may not be running!"
          exit 1
        fi
        
        if ! grep -q "JUnit 5 and junit-js framework are fully compatible" build.log; then
          echo "ERROR: JUnit 5 compatibility verification not found!"
          exit 1
        fi
        
        # Verify JUnit Platform is being used (indicates JUnit 5 support)
        if ! grep -q "JUnitPlatformProvider" build.log; then
          echo "ERROR: JUnit Platform Provider not detected!"
          exit 1
        fi
        
        # Check that we have both JUnit 5 tests (ModernJavaTest) and JUnit 4 tests (ExampleTestSuite)
        if ! grep -q "Tests run: 6.*ModernJavaTest" build.log; then
          echo "ERROR: Expected 'Tests run: 6' for ModernJavaTest not found - JUnit 5 tests may not be running!"
          grep "Tests run:" build.log || echo "No 'Tests run:' found at all"
          exit 1
        fi
        
        # Verify GraalVM tests are running
        echo "Checking GraalVM tests..."
        if ! grep -q "Tests run: 16.*GraalVMNodeJSCryptoJSTest" build.log; then
          echo "ERROR: Expected 'Tests run: 16' for GraalVMNodeJSCryptoJSTest not found - GraalVM crypto tests may not be running!"
          grep "Tests run:" build.log || echo "No 'Tests run:' found at all"
          exit 1
        fi
        
        # Check for GraalVM crypto test output
        if ! grep -q "✓ Basic SHA256 test passed" build.log; then
          echo "ERROR: GraalVM SHA256 test output not found - GraalVM crypto tests may not be running!"
          exit 1
        fi
        
        if ! grep -q "✓ Random hex test passed" build.log; then
          echo "ERROR: GraalVM random test output not found - GraalVM crypto tests may not be running!"
          exit 1
        fi
        
        if ! grep -q "✓ Password hashing with salt test passed" build.log; then
          echo "ERROR: GraalVM combined crypto test output not found - GraalVM crypto tests may not be running!"
          exit 1
        fi
        
        # Check for debug GraalVM tests
        if ! grep -q "DEBUG: Basic GraalVM JavaScript execution test completed successfully" build.log; then
          echo "ERROR: GraalVM basic debug test output not found!"
          exit 1
        fi
        
        echo "✅ SUCCESS: JUnit 4 JavaScript, JUnit 5 Java, and GraalVM tests are all running correctly"
        echo "✅ Found expected JavaScript console output: 'One == One', 'Hello World'"  
        echo "✅ Found expected JavaScript test count: 'Tests run: 5' for ExampleTestSuite"
        echo "✅ Found expected GraalVM crypto test count: 'Tests run: 16' for GraalVMNodeJSCryptoJSTest"
        echo "✅ Found expected total test count: 'Tests run: 31' (5 JS + 6 JUnit 5 + 4 GraalVM debug + 16 GraalVM crypto)"
        echo "✅ Found expected JUnit 5 test execution and compatibility verification"
        echo "✅ Found expected GraalVM crypto functionality: SHA256, random generation, combined operations"
        echo "✅ JUnit Platform Provider detected - JUnit 5 support is active"