name: CI

on:
  push:
    branches: [ main, develop, 'release/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        
    - name: Build and verify JavaScript tests are running
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Running mvn verify and checking JavaScript test execution..."
        
        # Run mvn verify and capture output (allow test failures for demo purposes)
        mvn verify 2>&1 | tee build.log || true
        
        # Check that JavaScript console output appears (proves JS tests ran)
        if ! grep -q "One == One" build.log; then
          echo "ERROR: JavaScript test 'One == One' output not found - JS tests may not be running!"
          exit 1
        fi
        
        if ! grep -q "Hello World" build.log; then
          echo "ERROR: JavaScript test 'Hello World' output not found - JS tests may not be running!"
          exit 1
        fi
        
        # Check that we ran the expected number of tests (10)
        if ! grep -q "Tests run: 10" build.log; then
          echo "ERROR: Expected 'Tests run: 10' not found - wrong number of tests executed!"
          grep "Tests run:" build.log || echo "No 'Tests run:' found at all"
          exit 1
        fi
        
        echo "✅ SUCCESS: JavaScript tests are running correctly"
        echo "✅ Found expected console output: 'One == One', 'Hello World'"  
        echo "✅ Found expected test count: 'Tests run: 10'"