name: CI

on:
  push:
    branches: [ main, develop, 'release/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        
    - name: Build and verify both JUnit 4 JS tests and JUnit 5 Java tests are running
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Running mvn verify and checking both JUnit 4 JavaScript and JUnit 5 Java test execution..."
        
        # Run mvn verify and capture output (allow test failures for demo purposes)
        mvn verify 2>&1 | tee build.log || true
        
        # Verify JUnit 4 JavaScript tests are running
        echo "Checking JUnit 4 JavaScript tests..."
        if ! grep -q "One == One" build.log; then
          echo "ERROR: JavaScript test 'One == One' output not found - JS tests may not be running!"
          exit 1
        fi
        
        if ! grep -q "Hello World" build.log; then
          echo "ERROR: JavaScript test 'Hello World' output not found - JS tests may not be running!"
          exit 1
        fi
        
        # Check that we ran the expected number of JavaScript tests (5)
        if ! grep -q "Tests run: 5.*ExampleTestSuite" build.log; then
          echo "ERROR: Expected 'Tests run: 5' for ExampleTestSuite not found - wrong number of JavaScript tests executed!"
          grep "Tests run:" build.log || echo "No 'Tests run:' found at all"
          exit 1
        fi
        
        # Check total test count (11 total: 5 JS + 6 JUnit 5)
        if ! grep -q "Tests run: 11, Failures: 0, Errors: 0, Skipped: 0" build.log; then
          echo "ERROR: Expected total 'Tests run: 11' not found - wrong total test count!"
          grep "Tests run:" build.log || echo "No 'Tests run:' found at all"
          exit 1
        fi
        
        # Verify JUnit 5 Java tests are running
        echo "Checking JUnit 5 Java tests..."
        if ! grep -q "Running JUnit 5" build.log; then
          echo "ERROR: JUnit 5 test output not found - JUnit 5 tests may not be running!"
          exit 1
        fi
        
        if ! grep -q "JUnit 5 and junit-js framework are fully compatible" build.log; then
          echo "ERROR: JUnit 5 compatibility verification not found!"
          exit 1
        fi
        
        # Verify both engines are detected and running
        if ! grep -q "JUnit Jupiter" build.log; then
          echo "ERROR: JUnit Jupiter engine not detected!"
          exit 1
        fi
        
        if ! grep -q "JUnit Vintage" build.log; then
          echo "ERROR: JUnit Vintage engine not detected!"
          exit 1
        fi
        
        echo "✅ SUCCESS: Both JUnit 4 JavaScript and JUnit 5 Java tests are running correctly"
        echo "✅ Found expected JavaScript console output: 'One == One', 'Hello World'"  
        echo "✅ Found expected JavaScript test count: 'Tests run: 5' for ExampleTestSuite"
        echo "✅ Found expected total test count: 'Tests run: 11' (5 JS + 6 JUnit 5)"
        echo "✅ Found expected JUnit 5 test execution and compatibility verification"
        echo "✅ Both JUnit Jupiter and JUnit Vintage engines are active"